import type {UnprefixedRuleOptions} from '@stylistic/eslint-plugin';
import type {RulesWithTypedOptions} from '../../types';

const rules: Partial<RulesWithTypedOptions<UnprefixedRuleOptions>> = {
    'array-bracket-spacing': ['error'],
    'arrow-spacing': ['error'],
    'block-spacing': ['error'],
    'comma-spacing': ['error'],
    'computed-property-spacing': ['error'],
    'function-call-spacing': ['error'],
    'generator-star-spacing': ['error', 'after'],
    'indent': ['error', 4, {
        SwitchCase: 1,
        flatTernaryExpressions: false,
        offsetTernaryExpressions: false,
    }],
    'indent-binary-ops': ['error', 4],
    'jsx-child-element-spacing': ['error'],
    'jsx-closing-tag-location': ['error', 'line-aligned'],
    'jsx-curly-spacing': ['error', 'never'],
    'jsx-equals-spacing': ['error'],
    'jsx-indent-props': ['error', {indentMode: 4, ignoreTernaryOperator: true}],
    'jsx-tag-spacing': ['error', {
        closingSlash: 'never',
        beforeSelfClosing: 'proportional-always',
        afterOpening: 'never',
        beforeClosing: 'proportional-always',
    }],
    'key-spacing': ['error'],
    'keyword-spacing': ['error'],
    'no-mixed-spaces-and-tabs': ['error'],
    'no-multi-spaces': ['error'],
    'no-tabs': ['error'],
    'no-trailing-spaces': ['error'],
    'no-whitespace-before-property': ['error'],
    'object-curly-spacing': ['error'],
    'rest-spread-spacing': ['error'],
    'semi-spacing': ['error'],
    'space-before-blocks': ['error'],
    'space-before-function-paren': ['error', {
        anonymous: 'always',
        named: 'never',
        asyncArrow: 'always',
        catch: 'always',
    }],
    'space-in-parens': ['error'],
    'space-infix-ops': ['error'],
    'space-unary-ops': ['error', {words: true, nonwords: false}],
    'spaced-comment': ['off'],
    'switch-colon-spacing': ['error'],
    'template-curly-spacing': ['error'],
    'template-tag-spacing': ['error'],
    'type-annotation-spacing': ['error'],
    'type-generic-spacing': ['error'],
    'type-named-tuple-spacing': ['error'],
    'yield-star-spacing': ['error', 'after'],
};

export default rules;
